language: ruby
rvm:
  - 2.2.5

addons:
  ssh_known_hosts: 51.15.170.106

install:
  - bundle install

script:
  - bundle exec jekyll build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f52c5bb56486_key -iv $encrypted_f52c5bb56486_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site dirtyhenry@51.15.170.106:/home/dirtyhenry/work/websites/bootstragram.com
  on:
    branch: master
