language: ruby
rvm:
  - 2.5.1

install:
  - make install

script:
  - make build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _site
  target-branch: gh-pages
  fqdn: bootstragram.com
  on:
    branch: master
