language: ruby
rvm:
  - 2.5.1

install:
  - make install

script:
  - make lint
  - make build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
