title: Bootstragram
repository:
  url: https://github.com/bootstragram/bootstragram-blog
  name: bootstragram/bootstragram-blog
url: https://bootstragram.com
permalink: /:categories/:title/
baseurl: /
destination: ./_site
hightligher: rouge
markdown: CommonMark
exclude:
  - "Gemfile.lock"
  - "Gemfile"
  - "LICENSE"
  - "Makefile"
  - "package.json"
  - "README.md"
  - "yarn.lock"
collections:
  - devtools_bookmarks
header_pages:
  - about.md
footer_pages:
  - archives.md

commonmark:
  extensions:
    - "table"
  options:
    - "SMART"
    - "FOOTNOTES"
    - "LIBERAL_HTML_TAG"
    - "UNSAFE"

theme: kids

kids:
  archives_path: 'archives/'
  home_posts: 5

plugins:
  - jekyll-liquify
  - jekyll-sitemap

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]