title: Bootstragram
repository:
  url: https://github.com/bootstragram/bootstragram-blog
  name: bootstragram/bootstragram-blog
url: https://bootstragram.com
description: >-
  Notes for myself and fellow programmers, 
  with a focus on iOS, Swift and web frontend development. 
  Since 2009.
permalink: /blog/:title/
baseurl: /
destination: ./_site
hightligher: rouge
markdown: CommonMark
exclude:
  - "Gemfile.lock"
  - "Gemfile"
  - "LICENSE"
  - "Makefile"
  - "package.json"
  - "README.md"
  - "yarn.lock"
collections:
  - devtools_bookmarks
header_pages:
  - about.md
footer_pages:
  - archives.md

commonmark:
  options:
    # Use smart punctuation (curly quotes, etc.).
    - SMART
    # Parse footnotes.
    - FOOTNOTES
    # Allow raw HTML (required for jekyll-assets to work properly).
    - UNSAFE
  extensions:
    - strikethrough
    - autolink
    - table
theme: kids

feed:
  categories:
    - ios

kids:
  archives_path: "archives/"
  home_posts: 5
  header_pages:
    - categories.md
    - about.md
  footer_pages:
    - archives.md
    - bookmarks.md

plugins:
  - jekyll-feed
  - jekyll-liquify
  - jekyll-sitemap
