url: https://bootstragram.com
permalink: /:categories/:title/
baseurl: /
destination: ./_site
sitemap:
  exclude:
    - "/.htaccess"
    - "/htaccess"
hightligher: rouge
markdown: CommonMark
exclude:
  - "deploy_rsa.enc"
  - "Gemfile.lock"
  - "Gemfile"
  - "LICENSE"
  - "Makefile"
  - "package.json"
  - "README.md"
  - "yarn.lock"
collections:
  - devtools_bookmarks

commonmark:
  extensions:
    - "table"
  options:
    - "SMART"
    - "FOOTNOTES"
    - "LIBERAL_HTML_TAG"
    - "UNSAFE"

plugins:
  - jekyll-sitemap
