url: https://bootstragram.com
permalink: /:categories/:title/
baseurl: /
destination: ./_site
hightligher: rouge
markdown: CommonMark
exclude:
  - "Gemfile.lock"
  - "Gemfile"
  - "LICENSE"
  - "Makefile"
  - "package.json"
  - "README.md"
  - "yarn.lock"
collections:
  - devtools_bookmarks

commonmark:
  extensions:
    - "table"
  options:
    - "SMART"
    - "FOOTNOTES"
    - "LIBERAL_HTML_TAG"
    - "UNSAFE"

plugins:
  - jekyll-liquify
  - jekyll-sitemap

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]