url: http://bootstragram.com
permalink:  /:categories/:title/
baseurl:    /
sitemap:
    exclude:
        - "/.htaccess"
        - "/htaccess"
hightligher: rouge
exclude: [ 'bower_components', 'node_modules', 'Gruntfile.js', 'bower.json' ]