url: http://bootstragram.com
permalink:  /:categories/:title/
baseurl:    /
destination: ./_site
sitemap:
    exclude:
        - "/.htaccess"
        - "/htaccess"
hightligher: rouge
exclude: [ 'bower_components', 'node_modules', 'Gruntfile.js', 'bower.json', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'Rakefile', 'package.json' ]

plugins:
  - jekyll-sitemap
