url: http://bootstragram.com
permalink:  /:categories/:title/
baseurl:    /
destination: /Users/mick/Developer/build/bootstragram-blog-gh-pages
sitemap:
    exclude:
        - "/.htaccess"
        - "/htaccess"
hightligher: rouge
exclude: [ 'bower_components', 'node_modules', 'Gruntfile.js', 'bower.json' ]

gems:
  - jekyll-sitemap
