url: https://bootstragram.com
permalink:  /:categories/:title/
baseurl:    /
destination: ./_site
sitemap:
    exclude:
        - "/.htaccess"
        - "/htaccess"
hightligher: rouge
exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'LICENSE'
    - 'README.md'
    - 'deploy_rsa.enc'


plugins:
  - jekyll-sitemap
